apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jcer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jcer
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jcer
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jcer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jcer
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jrqi-tenant/rhtap-demo-app/hacbs-test-project-jcer@sha256:960db0ab3dc2f101be535250433e7216f5b2a5c3330addaff40cf92ea75aa5a3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
